#!/bin/sh

set -e

PROVISION_EXTRA_SOURCE="provision_extra"
PROVISION_EXTRA_TARGET="vagrant-box-builder/provision/extra"
OUTPUT_TARGET="${PWD}/output"

container_cleanup() {
    container_id=$(docker ps --all --quiet --filter "name=${1}")
    if ! [ -z "${container_id}" ]; then
        docker rm \
            --force \
            --volumes \
            ${container_id}
    fi
}

cleanup_all() {
    for name in "patch-ubuntu-installer" "build-vagrant-box"; do
         container_cleanup "${name}"
    done
}

cleanup_all

(
    cd ubuntu-installer-patcher

    docker build \
        --tag ubuntu-installer-patcher \
        --force-rm \
        . \
        || cleanup_all

    docker run \
        --name patch-ubuntu-installer \
        --volume /mnt/share/ \
        ubuntu-installer-patcher \
        || cleanup_all
)

rm -rf "${PROVISION_EXTRA_TARGET}"
mkdir -p "${PROVISION_EXTRA_TARGET}"
for file in $(ls ${PROVISION_EXTRA_SOURCE}/*.sh 2> /dev/null); do
    cp -f "${PROVISION_EXTRA_SOURCE}/${file}" "${PROVISION_EXTRA_TARGET}"
done

(
    cd vagrant-box-builder

    docker build \
        --tag vagrant-box-builder \
        --force-rm \
        . \
        || cleanup_all

    docker run \
        --name build-vagrant-box \
        --privileged \
        --rm \
        --volume "${OUTPUT_TARGET}:/mnt/output" \
        --volumes-from patch-ubuntu-installer \
        vagrant-box-builder \
        || cleanup_all
)

cleanup_all
